version: "3.9"

services:
  db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
#    restart: always
    command: [ "mongod", "--quiet", "--logpath", "/dev/null" ]
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  server-app:
    container_name: api-server
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db

volumes:
  mongodb: